apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  encrypt-secret-key: TlZOQ1dxNEtFREhYTmpzYXpkR1gyb1oxCg== 
  jwt-secret-key: MXdIcVFGZFVsVXI1VFpOcjF3VENpdXlNMFZ5ZTJMNGpYCg==
  mysql_user: c3RldmV1c2Vy
  mysql_password: c3RldmVwdw==

