apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-green
  namespace: st-aline
  labels:
    app: underwriter-green
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: underwriter-green
  template:
    metadata:
      labels:
        app: underwriter-green
    spec:
      containers:
        - name: underwriter-green
          image: stevetan/underwriter-microservice:1.1
          ports:
            - containerPort: 8073
          env:
            - name: underwriter_APP_PORT
              value: "8071"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-name
