apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment-${DEPLOYMENT_COLOR}
  namespace: st-aline
  labels:
    app: user-${DEPLOYMENT_COLOR}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: user-${DEPLOYMENT_COLOR}
  template:
    metadata:
      labels:
        app: user-${DEPLOYMENT_COLOR}
    spec:
      containers:
        - name: aline-user-ms
          image: stevetan/user-microservice:1.1
          ports:
            - containerPort: 8089
          env:
            - name: APP_PORT
              value: "8089"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-name