apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-microservice-deployment
  labels:
    app: bank-microservice
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bank-microservice
  template:
    metadata:
      labels:
        app: bank-microservice
    spec:
      containers:
        - name: bank-microservice
          image: stevetan/bank-microservice:1.4
          ports:
            - containerPort: 8071
          env:
            - name: APP_PORT
              value: "8071"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-name
---
apiVersion: v1
kind: Service
metadata:
  name: bank-microservice
spec:
  type: NodePort
  selector:
    app: bank-microservice
  ports:
    - port: 8073
      targetPort: 8073
      nodePort: 30103