apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: transaction-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-microservice
  template:
    metadata:
      labels:
        app: transaction-microservice
    spec:
      containers:
        - name: transaction-microservice
          image: stevetan/transaction-microservice:1.1
          resources:
          ports:
            - containerPort: 8072
          env:
            - name: TRANSACTION_APP_PORT
              value: "8072"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-name
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-microservice
spec:
  type: NodePort
  selector:
    app: transaction-microservice
  ports:
    - port: 8072
      targetPort: 8072
      nodePort: 30102