apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
  labels:
    app: user-microservice
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: user-microservice 
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: stevetan/user-microservice:1.1
          ports:
            - containerPort: 8070
          env:
            - name: APP_PORT
              value: "8070"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql_password
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: encrypt-secret-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret-key
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: db-name
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice
spec:
  type: NodePort
  selector:
    app: user-microservice
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30100