---
- name: Terminate EC2 instances
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    aws_region: "us-west-2"
    ec2_tags:
      Name: "bastion-host"
      
  tasks:
    - name: Task 1 # Find EC2 Facts
      ec2_instance_facts:
        region: "{{ aws_region }}"
        filters:
          "tag:Type": "bastion-host"
      register: ec2_facts
    - name: Task2 # Kill EC2 Instance
      ec2:
      instance_ids: "{{ ec2.instances[0].instance_id}}"
      state: 'absent'
      region: "{{ lookup('env', 'aws_region') }}"
