---
- name: Terminate EC2 instances
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    aws_region: "us-west-2"
    ec2_tags:
      Name: "bastion-host"
  tasks:    
   - name: EC2 Facts
     ec2_instance_facts:
      region: us-west-2
      filters:
        "tag:Type": "bastion-host"
     register: ec2

   - name: Kill EC2 Instance
     ec2:
     instance_ids: "{{ item.instance_id }}"
     state: "{{ state }}"
     region: "{{ lookup('env', 'aws_region') }}"
     with_items: "{{ ec2.instances }}"
