- name: Update all packages
  hosts: all
  become: true
  tasks:
    - name: Update docker packages
      yum:
        name: docker
        state: latest
    - name: Ensure docker-compose is installed and available
      get_url: 
        url : "https://github.com/docker/compose/releases/download/v{{ compose_vers }}/docker-compose-{{ os }}"
        dest: /usr/local/bin/docker-compose
        mode: u+x,g+x
